version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "WxboySuper"
    groups:
      python-packages:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "WxboySuper"
    groups:
      npm-workspace:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/tools/route-editor"
    schedule:
      interval: "weekly"
    reviewers:
      - "WxboySuper"