module.exports = {
  testEnvironment: 'jsdom',
  roots: ['<rootDir>/src'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  transformIgnorePatterns: [
    '<rootDir>/node_modules/.pnpm/(?!(react-router|react-router-dom|@remix-run\\+router|uuid|@turf\\+.*|kdbush|geokdbush|tinyqueue|concaveman|point-in-polygon-hao|robust-predicates|rbush|quickselect|skmeans|marchingsquares|sweepline-intersections|d3-array|d3-geo|d3-voronoi|topojson-client|earcut|tslib|ol|firebase|@firebase\\+.*)@)',
    'node_modules/(?!.pnpm|react-router|react-router-dom|@remix-run/router|uuid|@turf|kdbush|geokdbush|tinyqueue|concaveman|point-in-polygon-hao|robust-predicates|rbush|quickselect|skmeans|marchingsquares|sweepline-intersections|d3-array|d3-geo|d3-voronoi|topojson-client|earcut|tslib|ol|firebase|@firebase)',
  ],
  moduleNameMapper: {
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/src/__mocks__/fileMock.js',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@turf/turf$': '<rootDir>/node_modules/.pnpm/@turf+turf@7.3.5/node_modules/@turf/turf/dist/cjs/index.cjs',
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx,js,jsx}',
    '!src/**/*.d.ts',
    '!src/setupTests.ts',
    '!src/index.tsx',
    '!src/reportWebVitals.ts',
    '!src/immerSetup.ts',
    '!src/testUtils.ts',
    '!src/**/index.ts',
    '!src/**/index.tsx',
    '!src/types/**',
    '!src/maps/contracts.ts',
    '!src/components/Map/OpenLayersForecastMap.tsx',
    '!src/components/Map/OpenLayersVerificationMap.tsx',
    '!src/hooks/useCloudCycles.ts',
    '!src/lib/cloudCyclesService.ts',
    '!src/pages/CloudLibraryPage.tsx',
    '!src/**/__mocks__/**',
  ],
  coveragePathIgnorePatterns: [
    '[/\\\\]src[/\\\\]index\\.tsx$',
    '[/\\\\]src[/\\\\]reportWebVitals\\.ts$',
    '[/\\\\]src[/\\\\]setupTests\\.ts$',
    '[/\\\\]src[/\\\\]immerSetup\\.ts$',
    '[/\\\\]src[/\\\\]testUtils\\.ts$',
    '[/\\\\]src[/\\\\]components[/\\\\]DaySelector[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]components[/\\\\]Layout[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]components[/\\\\]OutlookSelector[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]components[/\\\\]Toolbar[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]pages[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]store[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\]types[/\\\\].*',
    '[/\\\\]src[/\\\\]maps[/\\\\]contracts\\.ts$',
    '[/\\\\]src[/\\\\]components[/\\\\]Map[/\\\\]OpenLayersForecastMap\\.tsx$',
    '[/\\\\]src[/\\\\]components[/\\\\]Map[/\\\\]OpenLayersVerificationMap\\.tsx$',
    '[/\\\\]src[/\\\\]hooks[/\\\\]useCloudCycles\\.ts$',
    '[/\\\\]src[/\\\\]lib[/\\\\]cloudCyclesService\\.ts$',
    '[/\\\\]src[/\\\\]pages[/\\\\]CloudLibraryPage\\.tsx$',
    '[/\\\\]src[/\\\\].*[/\\\\]index\\.ts$',
    '[/\\\\]src[/\\\\].*[/\\\\]index\\.tsx$',
    '[/\\\\]src[/\\\\].*[/\\\\]__mocks__[/\\\\].*',
    '[/\\\\]src[/\\\\].*\\.d\\.ts$',
  ],
  coverageProvider: 'v8',
  coverageReporters: ['text', 'lcov', 'json-summary'],
};
