name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create static structure
        run: |
          mkdir -p _site/static/{data,images,styles}
          cp -r src/static/images/* _site/static/images/
          cp src/static/styles.css _site/static/styles/
          cp src/static/script.js _site/static/
          cp src/static/data/santa_route.json _site/static/data/
          cp src/index.html _site/
      
      - name: Generate static data
        run: python src/generate_static.py
      
      - name: Upload and deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4