name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create static site structure
        run: |
          mkdir -p _site/static/data
          mkdir -p _site/static/images
          mkdir -p _site/static/styles
          
          # Copy static assets
          cp src/static/images/* _site/static/images/
          cp src/static/styles.css _site/static/styles/
          cp src/static/script.js _site/static/
          cp src/static/data/santa_route.json _site/static/data/
          
          # Copy and rename template
          cp src/index.html _site/
          
          # Generate static data
          python src/generate_static.py
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4